language: java

jdk:
- openjdk11
- openjdk10
- oraclejdk9
- oraclejdk8

before_install:
- rm "${JAVA_HOME}/lib/security/cacerts"
- ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"